# Использование команд билиотеки NumPy

#### 1.1.	Создайте одномерный массив my_array, в котором по порядку все числа до 100, кратные 5

In [18]:
import numpy as np

my_array = np.arange(5, 101, 5)
my_array

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

#### 2.1.	Из полученного массива получить массив с кратными 10 числами

In [19]:
divisible_to_10 = my_array[my_array % 10 == 0]
divisible_to_10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

#### 3.1.	Получить двумерный массив с двумя столбцами

In [26]:
two_column_array = divisible_to_10.reshape(-1, 2)
two_column_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

#### 4.1.	Получите набор my_second_array, в котором все элементы меньше предыдущего исходного на 5

In [29]:
my_second_array = two_column_array - 5
my_second_array

array([[ 5, 15],
       [25, 35],
       [45, 55],
       [65, 75],
       [85, 95]])

#### 5.1.	Соедините массивы, полученные в п. 3.1 и 4.1, горизонтально. Используйте .T для транспонирования матрицы.

In [37]:
combined_array = np.hstack([two_column_array.T, my_second_array.T])
combined_array

array([[ 10,  30,  50,  70,  90,   5,  25,  45,  65,  85],
       [ 20,  40,  60,  80, 100,  15,  35,  55,  75,  95]])

#### 6.1.	Разделите 2 и 3 строку на 4 верхних строки my_array. Используйте .T для транспонирования матрицы

In [38]:
division_result = (combined_array[1:3] / my_array[:4].reshape(-1, 1)).T
division_result

array([[ 4.        ,  2.        ,  1.33333333,  1.        ],
       [ 8.        ,  4.        ,  2.66666667,  2.        ],
       [12.        ,  6.        ,  4.        ,  3.        ],
       [16.        ,  8.        ,  5.33333333,  4.        ],
       [20.        , 10.        ,  6.66666667,  5.        ],
       [ 3.        ,  1.5       ,  1.        ,  0.75      ],
       [ 7.        ,  3.5       ,  2.33333333,  1.75      ],
       [11.        ,  5.5       ,  3.66666667,  2.75      ],
       [15.        ,  7.5       ,  5.        ,  3.75      ],
       [19.        ,  9.5       ,  6.33333333,  4.75      ]])

#### 7.1.	Оставить только те значения, которые не изменились после деления

In [43]:
unchanged_values = division_result[division_result == np.floor(division_result)]
unchanged_values

array([ 4.,  2.,  1.,  8.,  4.,  2., 12.,  6.,  4.,  3., 16.,  8.,  4.,
       20., 10.,  5.,  3.,  1.,  7., 11., 15.,  5., 19.])

#### 8.1.	Снова получить трехстрочный двумерный массив и поменять местами первую и третью строки

In [48]:
modified_array = np.copy(division_result)
modified_array[[0,2]] = modified_array[[2,0]]
modified_array

array([[12.        ,  6.        ,  4.        ,  3.        ],
       [ 8.        ,  4.        ,  2.66666667,  2.        ],
       [ 4.        ,  2.        ,  1.33333333,  1.        ],
       [16.        ,  8.        ,  5.33333333,  4.        ],
       [20.        , 10.        ,  6.66666667,  5.        ],
       [ 3.        ,  1.5       ,  1.        ,  0.75      ],
       [ 7.        ,  3.5       ,  2.33333333,  1.75      ],
       [11.        ,  5.5       ,  3.66666667,  2.75      ],
       [15.        ,  7.5       ,  5.        ,  3.75      ],
       [19.        ,  9.5       ,  6.33333333,  4.75      ]])

#### 9.1.	Получить среднее, медиану и стандартное отклонение для каждой строки, используя команды np.mean(), np.median(), np.std().

In [61]:
means = np.mean(modified_array, axis=1)
print(means)
medians = np.median(modified_array, axis=1)
print(medians)
std_devs = np.std(modified_array, axis=1)
print(std_devs)

[ 6.25        4.16666667  2.08333333  8.33333333 10.41666667  1.5625
  3.64583333  5.72916667  7.8125      9.89583333]
[5.         3.33333333 1.66666667 6.66666667 8.33333333 1.25
 2.91666667 4.58333333 6.25       7.91666667]
[3.49106001 2.32737334 1.16368667 4.65474668 5.81843335 0.872765
 2.03645167 3.20013834 4.36382501 5.52751168]


#### 10.1.	Сделать нормализацию на максимальное значение вдоль строк, поделив каждый элемент массива на max() вдоль строк.

In [63]:
normalized_array = modified_array / np.max(modified_array, axis=1, keepdims=True)
normalized_array

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [1.        , 0.5       , 0.33333333, 0.25      ],
       [1.        , 0.5       , 0.33333333, 0.25      ],
       [1.        , 0.5       , 0.33333333, 0.25      ],
       [1.        , 0.5       , 0.33333333, 0.25      ],
       [1.        , 0.5       , 0.33333333, 0.25      ],
       [1.        , 0.5       , 0.33333333, 0.25      ],
       [1.        , 0.5       , 0.33333333, 0.25      ],
       [1.        , 0.5       , 0.33333333, 0.25      ],
       [1.        , 0.5       , 0.33333333, 0.25      ]])

# Использование команд библиотеки pandas

In [187]:
import pandas as pd

# 2.1 Импорт данных из CSV файла
df = pd.read_csv(r"Global Population Trends(2016-2022).csv")

# 2.2 Вывод первых нескольких записей таблицы
print("Первые несколько записей:")
print(df.head())

# 2.3 Определение размерности фрейма
print("Размерность фрейма:", df.shape)

# 2.4 Вывод названий столбцов
print("Названия заголовков столбцов:", df.columns)

# 2.5 Вывод информации о данных
print("Описание данных:")
print(df.info())

# 2.6 Удаление строк, где в столбце «Total Population» содержится символ "-"
df1 = df[df['Total Population'] != '-']

# Удаление запятых и преобразование столбца «Total Population» в числовой формат
df1.loc[:, 'Total Population'] = df1['Total Population'].str.replace(',', '').astype(float)

# 2.7 Описательная статистика по переменным
print("Описательная статистика:")
print(df1.describe())

# 2.8 Сортировка данных по «Total Population» и «Country»
df1_sorted = df1.sort_values(by=['Total Population', 'Country'], ascending=[False, True])
print("Отсортированные данные:")
print(df1_sorted.head())

# 2.9 Определение страны с максимальной численностью населения
max_population_country = df1.loc[df1['Total Population'].idxmax(), 'Country']
print("Страна с максимальной численностью населения:", max_population_country)

# 2.10 Определение страны с минимальной численностью населения
min_population_country = df1.loc[df1['Total Population'].idxmin(), 'Country']
print("Страна с минимальной численностью населения:", min_population_country)

# Убедитесь, что модуль openpyxl установлен для экспорта в Excel
# Если не установлен, выполните: pip install openpyxl

# 2.11 Экспорт данных в Excel файл
df1.to_excel("Global_Population_Trends_Exported.xlsx", index=False, engine='openpyxl')

Первые несколько записей:
       Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55            63.0      37.342       7.027          5.129   
1                 56            63.0      36.927       6.981          5.002   
2                 58            64.0      36.466       6.791           4.87   
3                 60            63.0      36.051       7.113           4.75   
4                  -            62.0      35.842       7.344          4.643   

  Infant Mortality Rate Growth Rate  
0         